apiVersion: v1
kind: Service
metadata:
  name: reinier-service
  labels:
    app: reinier-service
spec:
  ports:
    - port: 3434
      targetPort: 3434
    - port: 4369
      targetPort: 4369
      name: epmd
  selector:
    app: reinierservice
  type: NodePort